### ISSUE TITLE
Coingate Update for Omnipay 3.x?

### ISSUE THREAD

**Issue by PR4M** [coingate/omnipay-coingate#4]

**Comment by ghost** [comment]
i'll need it too

**Comment by vgumonis** [comment]
We have recently updated our omnipay package and made a release. You can activate omnipay 3 support by updating our package

**Comment by hashimaziz1** [comment]
> We have recently updated our omnipay package and made a release. You can activate omnipay 3 support by updating our package

Are you referring to this package? Does it now support V3? If so you should update the table on the [main Omnipay page](https://github.com/thephpleague/omnipay) (which is how I found this package) because it currently states the package only supports V2.
